### ISSUE TITLE
site-packages\detect_mask\Mask.py", line 8, in <module>     warnings.filterwarnings("ignore") NameError: name 'warnings' is not defined

### ISSUE THREAD

**Issue by httpanand** [Jash271/detect_mask#1]
```
site-packages\detect_mask\Mask.py", line 8, in <module>
    warnings.filterwarnings("ignore")
NameError: name 'warnings' is not defined
```

**Comment by Jash271** [comment]
Hi,
Thank you so much for bringing this to my notice,basically, I had to import warnings in the main Mask.py file.
I'll make the required changes and release a new version.

**Comment by httpanand** [comment]
Welcome 👍🏽

**Comment by Jash271** [comment]
Heyy, a new version of the package has been released, kindly try it out
